spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5433/finflow
    username: ${DB_USERNAME:finflow}
    password: ${DB_PASSWORD:finflow}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback-spring.xml